---
- name: Deploy Fairdata IDA Service
  hosts: idaappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-ida
    vars:
      prepare_application: False
      deploy_application: True
      update_proxy: False

      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      instance_name: '{{ ida_instance_name | default("ida") }}'

      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'

      rabbitmq_vhost: '{{ ida_rabbitmq_vhost | default("ida_vhost") }}'
      rabbitmq_worker_user: '{{ ida_rabbitmq_worker_user | default("worker") }}'
      rabbitmq_worker_pass: '{{ ida_rabbitmq_worker_pass | default("test") }}'

      # Repo variables
      # ~~~~~~~~~~~~~~~~~~~~~~~
      repo_ida_url: '{{ ida_repo_ida_url | default("https://github.com/CSCfi/ida2") }}'
      repo_ida_version: '{{ ida_repo_ida_version | default("master") }}'
      repo_ida_tools_url: '{{ ida_repo_ida_tools_url | default("https://github.com/CSCfi/ida2-command-line-tools") }}'
      repo_ida_tools_version: '{{ ida_repo_ida_tools_version | default("master") }}'

      # Configuration variables
      # ~~~~~~~~~~~~~~~~~~~~~~~
      metax_base_url: '{{ ida_metax_base_url | default("https://metax.fairdata.fi/") }}'
      metax_file_storage_id: '{{ ida_metax_file_storage_id | default("urn:nbn:fi:att:file-storage-ida") }}'
      metax_user: '{{ ida_metax_user | default("ida") }}'
      metax_pass: '{{ metax_application_ida_user_password | default("not-used") }}'
      sso_api_url: '{{ ida_sso_api_url | default("https://sso.fairdata.fi") }}'
      sso_api_domain: '{{ ida_sso_api_domain | default("fairdata.fi") }}'
      sso_authentication: '{{ ida_sso_authentication | default("false") }}'
      sso_key: '{{ ida_sso_key | default("secret") }}'
      ldap_host_url: '{{ ida_ldap_host_url | default("ldaps://ldap.example.com") }}'
      ldap_bind_user: '{{ ida_ldap_bind_user | default("uid=test,ou=Special Users,dc=csc,dc=fi") }}'
      ldap_password: '{{ ida_ldap_password | default("secret") }}'
      ldap_search_base: '{{ ida_ldap_search_base | default("ou=idm,dc=csc,dc=fi") }}'
      fdwe_url: '{{ ida_fdwe_url | default("https://matomo.fairdata.fi/fdwe.js") }}'
