---
- name: Deploy Fairdata IDA Service
  hosts: idafrontendservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-ida
    vars:
      # Control variables
      # ~~~~~~~~~~~~~~~~~
      update_git_repository: True
      delete_tests: True
      prepare_application: False
      deploy_application: False
      update_proxy: False

      # Repo variables
      # ~~~~~~~~~~~~~~
      repo_ida_url: '{{ ida_repo_url | default("https://github.com/CSCfi/ida2") }}'
      repo_ida_version: '{{ ida_repo_version | default("master") }}'
