---
- name: Prepare Fairdata IDA Service
  hosts: idaservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-python
    vars:
      install_method: '{{ fairdata_python_install_method | default("none") }}'
      version: '{{ fairdata_python_version | default("3.6.8") }}'
      minor_version: '{{ fairdata_python_minor_version | default("3.6") }}'
      python_executable: '{{ fairdata_python_python_executable | default("python3") }}'
      rpm_src: '{{ fairdata_python_rpm_src | default("") }}'
      rpm_dest: '{{ fairdata_python_rpm_dest | default("") }}'
  - role: fairdata-ansible-php
  - role: anxs.postgresql
    vars:
      postgresql_version: 9.6
      postgresql_data_directory: '{{ postgres_data_directory | default("/var/lib/pgsql/9.6/data") }}'
      postgresql_pg_hba_custom:
      - type: '{{ ida_database_type | default("host") }}'
        database: 'all'
        user: 'all'
        address: '{{ ida_database_address | default("127.0.0.1/32") }}'
        method: 'md5'
      postgresql_users:
      - name: '{{ ida_postgres_user | default("nextcloud") }}'
        pass: '{{ ida_postgres_password | default("nextcloud") }}'
      postgresql_user_privileges:
      - name: '{{ ida_postgres_user | default("nextcloud") }}'
        role_attr_flags: 'CREATEDB'
      postgresql_databases:
      - name: '{{ ida_postgres_db | default("nextcloud") }}'
        owner: '{{ ida_postgres_user | default("nextcloud") }}'
    become: yes
  - role: fairdata-ansible-rabbitmq
    vars:
      nodename: '{{ rabbitmq_nodename | default("rabbit") }}'
      vhosts:
        - '{{ ida_rabbitmq_vhost | default("ida_vhost") }}'
        - '{{ ida_rabbitmq_test_vhost | default("test-ida-vhost") }}'
      users:
        - user: '{{ ida_rabbitmq_admin_user | default("admin") }}'
          pass: '{{ ida_rabbitmq_admin_pass | default("test") }}'
          tags: 'administrator'
          permissions:
          - vhost: '{{ ida_rabbitmq_vhost | default("ida_vhost") }}'
            configure_priv: '^$'
            read_priv: '.*'
            write_priv: '.*'
          - vhost: '{{ ida_rabbitmq_test_vhost | default("test-ida-vhost") }}'
            configure_priv: '^$'
            read_priv: '.*'
            write_priv: '.*'
        - user: '{{ ida_rabbitmq_worker_user | default("worker") }}'
          pass: '{{ ida_rabbitmq_worker_pass | default("test") }}'
          permissions:
          - vhost: '{{ ida_rabbitmq_vhost | default("ida_vhost") }}'
            configure_priv: '^$'
            read_priv: '.*'
            write_priv: '.*'
  - role: fairdata-ansible-redis
    vars:
      bind_address: '{{ ida_redis_bind_address | default("0.0.0.0") }}'
  - role: fairdata-ansible-httpd
    vars:
      install_ssl_wildcard_certificate: '{{ fairdata_install_ssl_wildcard_certificate | default(False) }}'
      ssl_wildcard_certificate_src: '{{ fairdata_ssl_wildcard_certificate_src | default("") }}'
      ssl_wildcard_certificate_dest: '{{ fairdata_ssl_wildcard_certificate_dest | default("") }}'
      ssl_wildcard_certificate_key_src: '{{ fairdata_ssl_wildcard_certificate_key_src | default("") }}'
      ssl_wildcard_certificate_key_dest: '{{ fairdata_ssl_wildcard_certificate_key_dest | default("") }}'
    when: ida_configure_proxy | default(True)
  - role: fairdata-ansible-nginx
    vars:
      install_ssl_wildcard_certificate: '{{ fairdata_install_ssl_wildcard_certificate | default(False) }}'
      ssl_wildcard_certificate_src: '{{ fairdata_ssl_wildcard_certificate_src | default("") }}'
      ssl_wildcard_certificate_dest: '{{ fairdata_ssl_wildcard_certificate_dest | default("") }}'
      ssl_wildcard_certificate_key_src: '{{ fairdata_ssl_wildcard_certificate_key_src | default("") }}'
      ssl_wildcard_certificate_key_dest: '{{ fairdata_ssl_wildcard_certificate_key_dest | default("") }}'
    when: ida_use_nginx | default(False)
  - role: fairdata-ansible-ida
    vars:
      prepare_application: True
      deploy_application: False
      update_proxy: False
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
