---
- name: Prepare Fairdata IDA frontend servers
  hosts: idafrontendservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-python
    vars:
      install_method: '{{ fairdata_python_install_method | default("none") }}'
      version: '{{ fairdata_python_version | default("3.6.8") }}'
      minor_version: '{{ fairdata_python_minor_version | default("3.6") }}'
      python_executable: '{{ fairdata_python_python_executable | default("python3") }}'
      rpm_src: '{{ fairdata_python_rpm_src | default("") }}'
      rpm_dest: '{{ fairdata_python_rpm_dest | default("") }}'
  - role: fairdata-ansible-php
  - role: fairdata-ansible-httpd
    vars:
      install_ssl_wildcard_certificate: '{{ fairdata_install_ssl_wildcard_certificate | default(False) }}'
      ssl_wildcard_certificate_src: '{{ fairdata_ssl_wildcard_certificate_src | default("") }}'
      ssl_wildcard_certificate_dest: '{{ fairdata_ssl_wildcard_certificate_dest | default("") }}'
      ssl_wildcard_certificate_key_src: '{{ fairdata_ssl_wildcard_certificate_key_src | default("") }}'
      ssl_wildcard_certificate_key_dest: '{{ fairdata_ssl_wildcard_certificate_key_dest | default("") }}'
    when: ida_configure_proxy | default(True)
  - role: fairdata-ansible-nginx
    vars:
      configure_modular_nginx: False
      install_ssl_wildcard_certificate: '{{ fairdata_install_ssl_wildcard_certificate | default(False) }}'
      ssl_wildcard_certificate_src: '{{ fairdata_ssl_wildcard_certificate_src | default("") }}'
      ssl_wildcard_certificate_dest: '{{ fairdata_ssl_wildcard_certificate_dest | default("") }}'
      ssl_wildcard_certificate_key_src: '{{ fairdata_ssl_wildcard_certificate_key_src | default("") }}'
      ssl_wildcard_certificate_key_dest: '{{ fairdata_ssl_wildcard_certificate_key_dest | default("") }}'
    when: ida_use_nginx | default(False)
  - role: fairdata-ansible-ida
    vars:
      prepare_application: True
      deploy_application: False
      update_proxy: False
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
