---
- name: Prepare Fairdata IDA Database servers
  hosts: idadbservers
  remote_user: '{{ deployer }}'
  roles:
  - role: anxs.postgresql
    vars:
      postgresql_version: 9.6
      postgresql_data_directory: '{{ postgres_data_directory | default("/var/lib/pgsql/9.6/data") }}'
      postgresql_listen_addresses: '{{ ida_postgresql_listen_addresses | default(["localhost"]) }}'
      postgresql_pg_hba_custom:
      - type: '{{ ida_database_type | default("host") }}'
        database: 'all'
        user: 'all'
        address: '{{ ida_database_address | default("127.0.0.1/32") }}'
        method: 'md5'
      postgresql_users:
      - name: '{{ ida_postgres_user | default("nextcloud") }}'
        pass: '{{ ida_postgres_password | default("nextcloud") }}'
      postgresql_user_privileges:
      - name: '{{ ida_postgres_user | default("nextcloud") }}'
        role_attr_flags: 'CREATEDB'
      postgresql_databases:
      - name: '{{ ida_postgres_db | default("nextcloud") }}'
        owner: '{{ ida_postgres_user | default("nextcloud") }}'
    become: yes
