---
- import_playbook: prepare-ida-db-servers.yml
- import_playbook: prepare-ida-control-servers.yml
- import_playbook: prepare-ida-cache-servers.yml
- import_playbook: prepare-ida-frontend-servers.yml
- import_playbook: deploy-ida-service.yml
- import_playbook: update-ida-proxy.yml
- import_playbook: run-ida-tests.yml
  when: ida_run_tests | default(True)
