---
- name: Deploy Etsin-Search Service
  hosts: etsinqvaindataservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-etsin-qvain
    vars:
      deploy_app_server: False
      deploy_data_server: True
      prepare_application: True
      deploy_application: True
      run_tests: False
      configure_proxy: False
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'

      # Application variables
      # ~~~~~~~~~~~~~~~~~~~~~
      metax_qvain_api_password: '{{ metax_application_qvain_user_password | default("not_used") }}'
      metax_api_password: '{{ metax_application_etsin_user_password | default("not_used") }}'

      # Repository variables
      # ~~~~~~~~~~~~~~~~~~~~~
      repo_url_data: '{{ etsin_search_repo_url | default("https://github.com/CSCfi/etsin-finder-search.git") }}'
      repo_version: '{{ etsin_search_repo_version | default("master") }}'
