---
- name: Deploy Etsin-Qvain Service
  hosts: etsinqvainappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-etsin-qvain
    vars:
      deploy_app_server: True
      deploy_data_server: False
      prepare_application: False
      deploy_application: True
      manage_application: False
      run_tests: False
      configure_proxy: '{{ etsin_qvain_configure_proxy | default(True) }}'
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'

      # Repository variables
      # ~~~~~~~~~~~~~~~~~~~~~
      repo_url_app: '{{ etsin_qvain_repo_url | default("https://github.com/CSCfi/etsin-finder.git") }}'
      repo_version: '{{ etsin_qvain_repo_version | default("master") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'
