---
- name: Prepare Etsin Qvain app servers
  hosts: etsinqvainappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-etsin-qvain
    vars:
      deploy_app_server: False
      deploy_data_server: False
      prepare_application: False
      deploy_application: False
      run_tests: False
      configure_proxy: True
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'

      # Application variables
      # ~~~~~~~~~~~~~~~~~~~~~
      sso_key: '{{ etsin_qvain_sso_key | default("secret") }}'
      elasticsearch_hosts: '{{ etsin_qvain_elasticsearch_hosts | default("127.0.0.1") }}'
      metax_qvain_api_password: '{{ metax_application_qvain_user_password | default("not_used") }}'
      metax_api_password: '{{ metax_application_etsin_user_password | default("not_used") }}'
