---
- name: Update Etsin-Qvain web proxy
  hosts: etsinqvainappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-etsin-qvain
    vars:
      prepare_application: False
      deploy_application: False
      manage_application: False
      run_tests: False
      configure_proxy: '{{ etsin_qvain_configure_proxy | default(True) }}'
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
