---
- name: Manage DNS resolution
  hosts: all
  remote_user: '{{ deployer }}'
  tasks:
  - name: Ensure /etc/hosts includes wanted overrides
    lineinfile:
      path: '/etc/hosts'
      regexp: '{{ item.fqdn }}'
      line: '{{ item.address }} {{ item.fqdn }}'
    with_items: '{{ fairdata_host_overrides }}'
    become: 'yes'
