---
- name: Remove users
  gather_facts: false
  remote_user: '{{ deployer }}'
  become: true
  hosts: all
  vars:
    usernames: # add usernames as list to remove
      - 
  tasks:
    - name: Remove user
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      with_items: "{{ usernames }}"

...
