---
- name: Delete Metax API web proxy
  hosts: metaxappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-metax
    vars:
      prepare_application: False
      deploy_application: False
      manage_application: False
      run_tests: False
      configure_proxy: False
      delete_proxy: True
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
