---
- name: Deploy Metax API
  hosts: metaxappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-metax
    vars:
      prepare_application: False
      deploy_application: True
      manage_application: False
      run_tests: False
      configure_proxy: False
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      # Repo
      repo_url: '{{ metax_repo_url | default("https://github.com/CSCfi/metax-api.git") }}'
      repo_version: '{{ metax_repo_version | default("master") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'
      # Database
      application_database_host: '{{ metax_application_database_host | default("localhost") }}'
      application_database: '{{ metax_application_database | default("metax") }}'
      application_database_user: '{{ metax_application_database_user | default("metax") }}'
      application_database_password: '{{ metax_application_database_password | default("metax") }}'
      # Auth
      application_auth_server_logout_url: '{{ metax_application_auth_server_logout_url | default("https://aai.example.com/idp/profile/Logout") }}'
      # OAI
      application_oai_base_url: '{{ metax_application_oai_base_url | default("https://example.com/oai/") }}'
      application_oai_batch_size: '{{ metax_application_oai_batch_size | default("25") }}'
      application_oai_repository_name: '{{ metax_application_oai_repository_name | default("Metax") }}'
      application_oai_admin_email: '{{ metax_application_oai_admin_email | default("servicedesk@csc.fi") }}'
      # Datacite
      application_datacite_username: '{{ metax_application_datacite_username | default("user") }}'
      application_datacite_password: '{{ metax_application_datacite_password | default("secret") }}'
      application_datacite_prefix: '{{ metax_application_datacite_prefix | default("55.5555555") }}'
      application_datacite_url: '{{ metax_application_datacite_url | default("https://datacite.example.com") }}'
      # Rems
      application_rems_enabled: '{{ metax_application_rems_enabled | default("True") }}'
      application_rems_api_key: '{{ metax_application_rems_api_key | default("555") }}'
      application_rems_base_url: '{{ metax_application_rems_base_url | default("https://rems.example.com/api") }}'
      application_rems_metax_user: '{{ metax_application_rems_metax_user | default("metax@rems.example.com") }}'
      application_rems_reporter_user: '{{ metax_application_rems_reporter_user | default("reporter@rems.example.com") }}'
      application_rems_auto_approver: '{{ metax_application_rems_auto_approver | default("not-used") }}'
      application_rems_form_id: '{{ metax_application_rems_form_id | default("555") }}'
      # Users
      application_testaaja_consumer_password: '{{ metax_application_testaaja_consumer_password | default("not-set") }}'
      application_etsin_consumer_password: '{{ metax_application_etsin_consumer_password | default("not-set") }}'
      application_ttv_consumer_password: '{{ metax_application_ttv_consumer_password | default("not-set") }}'
      application_metax_user_password: '{{ metax_application_metax_user_password | default("not-set") }}'
      application_qvain_user_password: '{{ metax_application_qvain_user_password | default("not-set") }}'
      application_ida_user_password: '{{ metax_application_ida_user_password | default("not-set") }}'
      application_tpas_user_password: '{{ metax_application_tpas_user_password | default("not-set") }}'
      application_etsin_user_password: '{{ metax_application_etsin_user_password | default("not-set") }}'
      application_fds_user_password: '{{ metax_application_fds_user_password | default("not-set") }}'
      application_qvain_light_user_password: '{{ metax_application_qvain_light_user_password | default("not-set") }}'
      application_ttv_user_password: '{{ metax_application_ttv_user_password | default("not-set") }}'
      application_download_user_password: '{{ metax_application_download_user_password | default("not-set") }}'
