---
- name: Deploy Metax API
  hosts: metaxappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-metax
    vars:
      prepare_application: False
      deploy_application: True
      manage_application: False
      run_tests: False
      configure_proxy: False
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      # Repo
      repo_url: '{{ metax_repo_url | default("https://github.com/CSCfi/metax-api.git") }}'
      repo_version: '{{ metax_repo_version | default("master") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'
      # Database
      database_host: '{{ metax_database_host | default("localhost") }}'
      database_name: '{{ metax_database_name | default("metax") }}'
      database_user: '{{ metax_database_user | default("metax") }}'
      database_password: '{{ metax_database_password | default("metax") }}'
      # Elasticsearch
      elasticsearch_hosts: '{{ metax_elasticsearch_hosts | default("localhost") }}'
      elasticsearch_port: '{{ metax_elasticsearch_port | default(9200) }}'
      # Redis
      redis_host: '{{ metax_redis_bind_address | default("localhost") }}'
      redis_port: '{{ metax_redis_bind_port | default(6379) }}'
      redis_password: '{{ metax_redis_password | default("metax") }}'
      redis_use_password: '{{ metax_redis_use_password | default("false") }}'
      # Rabbitmq
      rabbitmq_hosts: '{{ metax_rabbitmq_hosts | default("localhost") }}'
      rabbitmq_use_vhost: '{{ metax_rabbitmq_use_vhost | default("on") }}'
      rabbitmq_vhost: '{{ metax_rabbitmq_vhost | default("metax") }}'
      rabbitmq_vhost_ttv: '{{ metax_rabbitmq_vhost_ttv | default("ttv") }}'
      rabbitmq_user: '{{ metax_rabbitmq_user | default("metax") }}'
      rabbitmq_password: '{{ metax_rabbitmq_password | default("metax") }}'
      # Application
      application_debug: '{{ metax_application_debug | default("False") }}'
      application_django_env: '{{ metax_application_django_env | default("test") }}'
      application_django_secret_key: '{{ metax_application_django_secret_key | default("secret") }}'
      # Auth
      application_auth_server_logout_url: '{{ metax_application_auth_server_logout_url | default("https://aai.example.com/idp/profile/Logout") }}'
      # OAI
      application_oai_batch_size: '{{ metax_application_oai_batch_size | default("25") }}'
      application_oai_repository_name: '{{ metax_application_oai_repository_name | default("Metax") }}'
      application_oai_admin_email: '{{ metax_application_oai_admin_email | default("servicedesk@csc.fi") }}'
      # Datacite
      application_datacite_username: '{{ metax_application_datacite_username | default("user") }}'
      application_datacite_password: '{{ metax_application_datacite_password | default("secret") }}'
      application_datacite_prefix: '{{ metax_application_datacite_prefix | default("55.5555555") }}'
      application_datacite_url: '{{ metax_application_datacite_url | default("https://datacite.example.com") }}'
      # Rems
      application_rems_enabled: '{{ metax_application_rems_enabled | default("True") }}'
      application_rems_api_key: '{{ metax_application_rems_api_key | default("555") }}'
      application_rems_base_url: '{{ metax_application_rems_base_url | default("https://rems.example.com/api") }}'
      application_rems_metax_user: '{{ metax_application_rems_metax_user | default("metax@rems.example.com") }}'
      application_rems_reporter_user: '{{ metax_application_rems_reporter_user | default("reporter@rems.example.com") }}'
      application_rems_auto_approver: '{{ metax_application_rems_auto_approver | default("not-used") }}'
      application_rems_form_id: '{{ metax_application_rems_form_id | default("555") }}'
      # Users
      application_api_users: '{{ metax_application_api_users | default([]) }}'
