---
- name: Prepare Metax API app servers
  hosts: metaxappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-python
    vars:
      python_executable: '{{ fairdata_python_python_executable | default("python3") }}'
      install_method: '{{ fairdata_python_install_method | default("none") }}'
      version: '{{ fairdata_python_version | default("3.6.8") }}'
      minor_version: '{{ fairdata_python_minor_version | default("3.6") }}'
      rpm_src: '{{ fairdata_python_rpm_src | default("") }}'
      rpm_dest: '{{ fairdata_python_rpm_dest | default("") }}'
  - role: fairdata-ansible-redis
    vars:
      bind_address: '{{ metax_redis_bind_address | default("0.0.0.0") }}'
  - role: fairdata-ansible-nginx
    vars:
      install_shared_ssl_certificate: '{{ metax_install_shared_ssl_certificate | default(False) }}'
      ssl_shared_certificate_src: '{{ fairdata_ssl_shared_certificate_src | default("") }}'
      ssl_shared_certificate_dest: '{{ fairdata_ssl_shared_certificate_dest | default("") }}'
      ssl_shared_certificate_key_src: '{{ fairdata_ssl_shared_certificate_key_src | default("") }}'
      ssl_shared_certificate_key_dest: '{{ fairdata_ssl_shared_certificate_key_dest | default("") }}'
    when: metax_configure_proxy | default(True)
  - role: fairdata-ansible-httpd
    vars:
      install_shared_ssl_certificate: False
    when: metax_configure_proxy | default(True)
  - role: fairdata-ansible-metax
    vars:
      prepare_application: True
      deploy_application: False
      manage_application: False
      run_tests: False
      configure_proxy: '{{ metax_configure_proxy | default(True) }}'
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      python_virtualenv_command: '{{ fairdata_python_virtualenv_command | default("virtualenv") }}'
      # OIDC
      oidc_auth_server_url: '{{ metax_oidc_auth_server_url }}'
      oidc_provider_metadata_url: '{{ metax_oidc_provider_metadata_url }}'
      oidc_auth_verify_jwks_uri: '{{ metax_oidc_auth_verify_jwks_uri }}'
      oidc_client_id: '{{ metax_oidc_client_id }}'
      oidc_client_secret: '{{ metax_oidc_client_secret }}'
      oidc_crypto_passphrase: '{{ metax_oidc_crypto_passphrase }}'
      oidc_id_token_iat_slack: '{{ metax_oidc_id_token_iat_slack }}'
      # Users
      application_testaaja_consumer_password: '{{ metax_application_testaaja_consumer_password | default("not-set") }}'
      application_etsin_consumer_password: '{{ metax_application_etsin_consumer_password | default("not-set") }}'
      application_ttv_consumer_password: '{{ metax_application_ttv_consumer_password | default("not-set") }}'
      application_metax_user_password: '{{ metax_application_metax_user_password | default("not-set") }}'
      application_qvain_user_password: '{{ metax_application_qvain_user_password | default("not-set") }}'
      application_ida_user_password: '{{ metax_application_ida_user_password | default("not-set") }}'
      application_tpas_user_password: '{{ metax_application_tpas_user_password | default("not-set") }}'
      application_etsin_user_password: '{{ metax_application_etsin_user_password | default("not-set") }}'
      application_fds_user_password: '{{ metax_application_fds_user_password | default("not-set") }}'
      application_qvain_light_user_password: '{{ metax_application_qvain_light_user_password | default("not-set") }}'
      application_ttv_user_password: '{{ metax_application_ttv_user_password | default("not-set") }}'
      application_download_user_password: '{{ metax_application_download_user_password | default("not-set") }}'
