---
- name: Prepare Metax API DB servers
  hosts: metaxdbservers
  remote_user: '{{ deployer }}'
  roles:
  - role: anxs.postgresql
    vars:
      postgresql_version: 9.6
      postgresql_data_directory: '{{ postgres_data_directory | default("/var/lib/pgsql/9.6/data") }}'
      postgresql_pg_hba_custom:
      - type: '{{ metax_database_type | default("host") }}'
        database: '{{ metax_database_name | default("metax") }}'
        user: '{{ metax_database_user | default("metax") }}'
        address: '{{ metax_database_allowed_subnet | default("127.0.0.1/32") }}'
        method: 'md5'
      - type: '{{ metax_test_database_type | default("host") }}'
        database: '{{ metax_test_database_name | default("test_metax") }}'
        user: '{{ metax_test_database_user | default("metax") }}'
        address: '{{ metax_database_allowed_subnet | default("127.0.0.1/32") }}'
        method: 'md5'
      postgresql_users:
      - name: '{{ metax_database_user | default("metax") }}'
        pass: '{{ metax_database_password | default("metax") }}'
      postgresql_user_privileges:
      - name: '{{ metax_database_user | default("metax") }}'
        role_attr_flags: 'CREATEDB'
      postgresql_databases:
      - name: '{{ metax_database_name | default("metax") }}'
        owner: '{{ metax_database_user | default("metax") }}'
      postgresql_listen_addresses:
      - '{{ metax_database_host | default("localhost") }}'
    become: yes
