---
- name: Update Metax API web proxy
  hosts: metaxappservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-metax
    vars:
      prepare_application: False
      deploy_application: False
      manage_application: False
      run_tests: False
      configure_proxy: '{{ metax_configure_proxy | default(True) }}'
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      # OIDC
      oidc_auth_server_url: '{{ metax_oidc_auth_server_url }}'
      oidc_provider_metadata_url: '{{ metax_oidc_provider_metadata_url }}'
      oidc_auth_verify_jwks_uri: '{{ metax_oidc_auth_verify_jwks_uri }}'
      oidc_client_id: '{{ metax_oidc_client_id }}'
      oidc_client_secret: '{{ metax_oidc_client_secret }}'
      oidc_crypto_passphrase: '{{ metax_oidc_crypto_passphrase }}'
      oidc_id_token_iat_slack: '{{ metax_oidc_id_token_iat_slack }}'
