---
- name: Prepare Fairdata Download Service
  hosts: downloadservers
  remote_user: '{{ deployer }}'
  roles:
  # This task has been disabled until further notice 
  # due to different behavior on different host systems
  # - role: fairdata-ansible-mounts
  #  vars:
  #    ext4_mounts: '{{ download_ext4_mounts | default([]) }}'
  #    bind_mounts: '{{ download_bind_mounts | default([]) }}'
  - role: fairdata-ansible-rabbitmq
    vars:
      nodename: '{{ rabbitmq_nodename | default("rabbit") }}'
      vhosts:
        - '{{ download_rabbitmq_vhost | default("download") }}'
      users:
        - user: '{{ download_rabbitmq_user | default("download") }}'
          pass: '{{ download_rabbitmq_pass }}'
          permissions:
          - vhost: '{{ download_rabbitmq_vhost | default("download") }}'
            configure_priv: .*
            read_priv: .*
            write_priv: .*
  - role: fairdata-ansible-nginx
    vars:
      configure_modular_nginx: True
      install_ssl_wildcard_certificate: '{{ fairdata_install_ssl_wildcard_certificate | default(False) }}'
      ssl_wildcard_certificate_src: '{{ fairdata_ssl_wildcard_certificate_src | default("") }}'
      ssl_wildcard_certificate_dest: '{{ fairdata_ssl_wildcard_certificate_dest | default("") }}'
      ssl_wildcard_certificate_key_src: '{{ fairdata_ssl_wildcard_certificate_key_src | default("") }}'
      ssl_wildcard_certificate_key_dest: '{{ fairdata_ssl_wildcard_certificate_key_dest | default("") }}'
  - role: fairdata-ansible-python
    vars:
      install_method: '{{ fairdata_python_install_method | default("none") }}'
      version: '{{ fairdata_python_version | default("3.6.8") }}'
      minor_version: '{{ fairdata_python_minor_version | default("3.6") }}'
      python_executable: '{{ fairdata_python_python_executable | default("python3") }}'
      rpm_src: '{{ fairdata_python_rpm_src | default("") }}'
      rpm_dest: '{{ fairdata_python_rpm_dest | default("") }}'
  - role: fairdata-ansible-download-service
    vars:
      prepare_application: True
      deploy_application: False
