---
- name: Update Fairdata Download Service proxy servers
  hosts: downloadservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-download-service
    vars:
      prepare_application: False
      deploy_application: False
      configure_nginx: True
      instance_domain: '{{ fairdata_domain | default("fairdata.fi") }}'
      nginx_public_port: '{{ download_nginx_public_port | default(4430) }}'
      nginx_internal_port: '{{ download_nginx_internal_port | default(4431) }}'
      nginx_custom_certificates: '{{ download_nginx_custom_certificates | default(False) }}'
      nginx_ssl_certificate: '{{ download_nginx_ssl_certificate | default("") }}'
      nginx_ssl_certificate_key: '{{ download_nginx_ssl_certificate_key | default("") }}'
