---
- name: Update data servers
  hosts: dataservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-rabbitmq
    vars:
      nodename: '{{ rabbitmq_nodename | default("rabbit") }}'
      vhosts:
        - '{{ download_application_rabbitmq_vhost | default("download") }}'
      users:
        - user: '{{ download_application_rabbitmq_user | default("download") }}'
          pass: '{{ download_application_rabbitmq_pass }}'
          permissions:
          - vhost: '{{ download_application_rabbitmq_vhost | default("download") }}'
            configure_priv: .*
            read_priv: .*
            write_priv: .*

- name: Deploy Fairdata Download Service
  hosts: downloadservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-nginx
    vars:
      disable_selinux: '{{ download_disable_selinux }}'
      configure_nginx: '{{ download_configure_nginx | default(False) }}'
      install_secrets: '{{ download_nginx_install_secrets | default(False) }}'
      ssl_secrets:
        - src: '{{ download_nginx_ssl_certificate_source }}'
          dest: '{{ download_nginx_ssl_certificate }}'
        - src: '{{ download_nginx_ssl_certificate_key_source }}'
          dest: '{{ download_nginx_ssl_certificate_key }}'
  - role: fairdata-ansible-python
    vars:
      python_executable: '{{ python_python_executable | default("python3") }}'
      install_method: '{{ python_install_method | default("none") }}'
      version: '{{ python_version | default("3.6.8") }}'
      minor_version: '{{ python_minor_version | default("3.6") }}'
      rpm_src: '{{ python_rpm_src | default("") }}'
      rpm_dest: '{{ python_rpm_dest | default("") }}'
  - role: fairdata-ansible-download-service
    vars:
      mount_volumes: '{{ download_mount_volumes | default(False) }}'
      cache_device: '{{ download_cache_device | default(False) }}'
      ida_storage_source: '{{ download_ida_storage_source }}'
      cache_root: '{{ download_cache_root }}'
      ida_storage_root: '{{ download_ida_storage_root }}'
      repo_install_method: '{{ download_repo_install_method | default("pull") }}'
      repo_deploy_key: '{{ download_repo_deploy_key }}'
      repo_url: '{{ download_repo_url }}'
      repo_version: '{{ download_repo_version | default("master") }}'
      repo_src: '{{ download_repo_src }}'
      repo_dest_root: '{{ download_repo_dest_root | default("/opt") }}'
      virtualenv_command: '{{ download_virtualenv_command | default("virtualenv") }}'
      application_environment: '{{ download_application_environment | default("development") }}'
      application_rabbitmq_host: '{{ download_application_rabbitmq_host | default("localhost") }}'
      application_rabbitmq_vhost: '{{ download_application_rabbitmq_vhost | default("download") }}'
      application_rabbitmq_user: '{{ download_application_rabbitmq_user | default("download") }}'
      application_rabbitmq_pass: '{{ download_application_rabbitmq_pass }}'
      application_jwt_secret: '{{ download_application_jwt_secret }}'
      application_service_metax_url: '{{ download_application_service_metax_url }}'
      application_service_metax_user: '{{ download_application_service_metax_user }}'
      application_service_metax_pass: '{{ download_application_service_metax_pass }}'
      public_port: '{{ download_public_port | default(4430) }}'
      internal_port: '{{ download_internal_port | default(4431) }}'
      host: '{{ download_host | default("0.0.0.0") }}'
      daemonize_server: '{{ download_daemonize_server | default(False) }}'
      daemonize_generator: '{{ download_daemonize_generator | default(False) }}'
      nginx_custom_certificates: '{{ download_nginx_custom_certificates | default("False") }}'
      nginx_ssl_certificate: '{{ download_nginx_ssl_certificate | default("/etc/pki/tls/certs/download.local.crt") }}'
      nginx_ssl_certificate_key: '{{ download_nginx_ssl_certificate_key | default("/etc/pki/tls/private/download.local.key") }}'
