---
- name: Deploye Elasticsearch
  hosts: dataservers
  remote_user: '{{ deployer }}'
  roles:
  - role: ansible-elasticsearch
    vars:
      es_config:
        bootstrap.memory_lock: true
        cluster.name: '{{ elasticsearch_cluster_name | default("test-cluster") }}'
        es_api_port: '{{ elasticsearch_http_port | default(9200) }}'
        http.port: '{{ elasticsearch_http_port | default(9200) }}'
        node.data: false
        node.master: true
        node.name: '{{ elasticsearch_node_name | default("node1") }}'
        transport.port: '{{ elasticsearch_transport_port | default(9300) }}'
      es_heap_size: '{{ elasticsearch_heap_size | default("256m")}}'
      es_use_repository: true
      es_version: '{{ elasticsearch_version | default("7.8.0") }}'
      es_version_lock: true
      es_xpack_features: []
