---
- name: Prepare DB servers
  hosts: dbservers
  remote_user: '{{ deployer }}'
  roles:
  - role: fairdata-ansible-postgresql
    vars:
      data_directory: '{{ postgres_data_directory | default("/var/lib/pgsql/9.6/data") }}'
      listen_addresses: '{{ postgres_listen_addresses | default("localhost") }}'
      users: '{{ postgres_users | default([]) }}'
      databases: '{{ postgres_databases | default([]) }}'
      allowed_connections: '{{ postgres_allowed_connections | default([]) }}'
